# This is a basic workflow to help you get started with Actions

name: Treble Creator

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      device:
        description: "Device Model Number"
        required: True
        type: choice
        options:
          - SM-T220
      region:
        description: "Device Region"
        required: true
        type: choice
        options:
          - BTU

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Dependencies
        run: |
          sudo apt-get install simg2img lz4
          pip3 install git+https://github.com/samloader/samloader.git
          echo $GITHUB_WORKSPACE
          echo ${{ github.event.inputs.device }}
          echo ${{ github.event.inputs.region }}
      
      - name: Download Firmware
        run: |
          FWV=$(samloader -m ${{ github.event.inputs.device }} -r ${{ github.event.inputs.region }} checkupdate)
          echo $FWV


