# This is a basic workflow to help you get started with Actions

name: Treble Creator

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      device:
        description: "Device Model Number"
        required: True
        type: choice
        options:
          - SM-T225
      region:
        description: "Device Region"
        required: true
        type: choice
        options:
          - BTU

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Add OTATools PATH Environment
        run: |
          export PATH=$PATH:/home/runner/work/SamsungTrebleMaker/SamsungTrebleMaker/otatools/bin/

      - name: Install Dependencies
        run: |
          sudo apt-get install simg2img lz4 unzip
          pip3 install git+https://github.com/samloader/samloader.git
          echo $GITHUB_WORKSPACE
          echo ${{ github.event.inputs.device }}
          echo ${{ github.event.inputs.region }}
      
      - name: Download and Decrypt Firmware
        run: |
          FWFileName="latestFW.zip.enc4"
          export FMV=$(samloader -m ${{ github.event.inputs.device }} -r ${{ github.event.inputs.region }} checkupdate)
          echo $FMV
          echo "Downloading latest update"
          samloader -m ${{ github.event.inputs.device }} -r ${{ github.event.inputs.region }} download -v $(echo $FMV) -o $(echo $FWFileName)
          echo "Decrypting Update Files"
          samloader -m ${{ github.event.inputs.device }} -r ${{ github.event.inputs.region }} decrypt -v $(echo $FMV) -i $(echo $FWFileName) -V 4 -o latestFW.zip
        
      - name: Unzip Firmware and Extract AP
        run: |
          echo $FMV
          mkdir APFiles
          unzip latestFW.zip
          ls -l
          mv AP_*.tar.md5 ./APFiles
          cd APFiles
          mkdir APExtracted
          ls -l
          tar -xf AP_*.tar.md5 --verbose -C ./APExtracted
          
      - name: Measure and unpack super image
        run: |
          cd APFiles/APExtracted
          lz4 -d super.img.lz4 super.img
          simg2img super.img super.ext4.img
          OG_SUPER_SIZE=$(stat -c '%n %s' super.ext4.img)
          
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          # The token used to authenticate.
          token: ${{ github.token }}
          # The name of the repository.
          repository:  ${{ github.repository }}
          # The number of days.
          retain_days: 0
          # The minimum runs to keep for each workflow.
          keep_minimum_runs: 0
          


